import { Component, signal } from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  imports: [],
  templateUrl: './input-button-unit.html',
  styleUrl: './input-button-unit.scss',
})
export class InputButtonUnit {
  title = signal('input text here');

  constructor() {
    setTimeout(() => {
      this.title.set('This is not the title you are looking for');
    }, 3000);
  }

  generateTitle(): string {
    return 'This title was generated by a method.';
  }

  changeTitle(newTitle: string) {
    this.title.set(newTitle);
  }

  getInputValue(event: Event) {
    return (event.target as HTMLInputElement).value;
  }
}

// signal w exporcie + set w timeout + set w changetitle + pamiętaj zaimportować!
