import { Component } from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  imports: [],
  templateUrl: './input-button-unit.html',
  styleUrl: './input-button-unit.scss',
})
export class InputButtonUnit {
  title = 'input text here';

  constructor() {
    setTimeout(() => {
      this.title = 'This is not the title you are looking for';
    }, 3000);
  }

  generateTitle(): string {
    return 'This title was generated by a method.';
  }
}
