import { Component, OnInit, signal, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  imports: [],
  templateUrl: './input-button-unit.html',
  styleUrl: './input-button-unit.scss',
})
export class InputButtonUnit implements OnInit {
  title = signal('input text here');

  constructor() {
    // setTimeout(() => {
    //   this.title.set('This is not the title you are looking for');
    // }, 3000);
  }

  ngOnInit(): void {}

  generateTitle(): string {
    return 'This title was generated by a method.';
  }

  changeTitle(newTitle: string) {
    this.title.set(newTitle);
  }

  getInputValue(event: Event) {
    return (event.target as HTMLInputElement).value;
  }

  @Output() submit: EventEmitter<string> = new EventEmitter<string>();

  submitValue(newTitle: string) {
    this.submit.emit(newTitle);
  }
}



// signal w exporcie + set w timeout + set w changetitle + pamiętaj zaimportować!
